// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Security Note: Using localStorage for session tokens.
// For production, configure Supabase to use httpOnly cookies via:
// 1. Enable "Enable Cookie" in Supabase Dashboard > Authentication > Settings
// 2. Set auth.flowType to 'pkce' in your Supabase project settings
// This helps mitigate XSS attacks that could steal session tokens

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true,
  }
});